required_approvals = 1
block_labels = ["wip"]
delete_merged_branches = true
status = [
    "Check (stm32f0)",
    "Check (stm32f1)",
    "Check (stm32f2)",
    "Check (stm32f3)",
    "Check (stm32f4)",
    "Check (stm32f7)",
    "Check (stm32h7)",
    "Check (stm32l0)",
    "Check (stm32l1)",
    "Check (stm32l4)",
    "Check (stm32l5)",
    "Check (stm32g0)",
    "Check (stm32g4)",
    "Check (stm32mp1)",
    "Check (stm32wl)",
    "Check (stm32wb)",
]
